[package]
name = "bitcoin-script-opcodes"
version = "0.1.0"
edition = "2021"
description = "A collection of opcodes used in Bitcoin Script"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
